
name: toy_nlp
task: nlp
data:
  train: data/nlp_train.csv
  test: data/nlp_test.csv
  text_col: text
  label_col: label
cv:
  folds: 5
model:
  name: distilbert-base-uncased
train:
  epochs: 1
  batch_size: 8
  lr: 2e-5
  max_len: 128
output:
  dir: outputs
  label: prediction
