
name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps (minimal)
        run: |
          python -m pip install -U pip
          # install only what the smoke test needs
          pip install typer pyyaml numpy pandas scikit-learn lightgbm joblib scipy optuna kaggle pytest
      - name: Run smoke tests
        run: pytest -q
